### PR TITLE
#29: Merging apigateway into development

### PR DESCRIPTION
**Pull request by SaintAngeLs**
Adding the Api with

### CODE REVIEW

**Comment by SaintAngeLs** [comment]
The parcels service and the orders services are taken as the example api endpoints

**Comment by eggwhat** [comment]
While using swagger, request urls are missing a slash. Adding slash in path property in ntrada.yml seems to fix this issue.
image

**Comment by SaintAngeLs** [comment]
> While using swagger, request urls are missing a slash. Adding slash in path property in ntrada.yml seems to fix this issue. image

Thank, you, that's correct, changing the path resolves the issue.

**Comment by SaintAngeLs** [comment]
There is one more issue with the availability service.

**Review by eggwhat — APPROVED** [review]
It will need later changes to adjust to the services
The new Pr will be created

**Pull request merged**
