### PR TITLE
Apigateway revamp

### PR DESCRIPTION
**Pull request by eggwhat**
please check #96 if it works

### CODE REVIEW

**Review by SaintAngeLs — APPROVED** [review]
Do you need the / in the routes? In the case yes, there will be a need to create the issue to remember that the axios requests should not handle it.

**Comment by eggwhat** [comment]
> Do you need the / in the routes? In the case yes, there will be a need to create the issue to remember that the axios requests should not handle it.

I added it so swagger would work properly, but it is not crucial to have swagger working. If it creates any issues i will remove it.

**Comment by SaintAngeLs** [comment]
> > Do you need the / in the routes? In the case yes, there will be a need to create the issue to remember that the axios requests should not handle it.
> 
> I added it so swagger would work properly, but it is not crucial to have swagger working. If it creates any issues i will remove it.
Leave is for the swagger documentation.

**Comment by SaintAngeLs** [comment]
> Leave is for the swagger documentation.

Leave is for the swagger documentation.

**Review by SaintAngeLs — APPROVED** [review]
Nice

**Pull request merged**
